---
- name: Clean up Front Ends
  hosts: tag_AnsibleGroup_frontends
  become: true
  roles:
    - clean-3-tier

- name: Clean up App
  hosts: tag_AnsibleGroup_apps
  become: true
  roles:
    - clean-3-tier

- name: Clean up App DBs
  hosts: tag_AnsibleGroup_appdbs
  become: true
  roles:
- clean-3-tier
