---
- name: Fetch Private Key from Bastion
  hosts: bastion
  gather_facts: true
  become: yes

  tasks:
  - name: Install python-pip
    yum:
     name: python-pip
     state: latest

  - name: Install ansible-tower-cli with pip
    pip:
      name: ansible-tower-cli

  - name: Inject Key into Ansible Tower
    tower_credential:
      name: Three_Tier_Prod_Key
      organization: Default
      state: present
      tower_host: tower1.db55.example.opentlc.com
      tower_username: admin
      tower_password: r3dh4t1!
      kind: ssh
      username: ec2-user
      ssh_key_data: "/root/.ssh/{{[inventory_hostname]['ec2_tag_Project'] | regex_replace('three-tier-app-','')}}key.pem"
