---
- hosts: tag_AnsibleGroup_bastions
  name: Fetch Private Keys
  gather_facts: true
  become: yes

  tasks:
  - name: Install python-pip
    yum:
      name: python-pip
      state: latest

  - name: Install Ansible tower CLI
    pip:
      name: ansible-tower-cli

  - name: Inject keys into ansible Tower
    tower_credential:
      name: Three_Tier_Prod_Key
      state: present
      organization: Default
      tower_host: "{{ tower_node }}.{{ tower_guid }}.{{ tower_domain_path }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      kind: ssh
      username: "{{ three_tier_user }}"
      ssh_key_data: "/root/.ssh/{{ hostvars[inventory_hostname]['ec2_tag_Project'] | regex_replace('three-tier-app-','') }}key.pem"
