---
- name: Provision Production Environment
  hosts: bastion
  gather_facts: true
  become: yes

  tasks:
  - name: Create bin directory
    file:
      path: "/root/bin"
      state: directory
      mode: 0777

  - name: Download common.sh and order_svc.sh
    get_url:
      url: http://www.opentlc.com/download/ansible_bootcamp/scripts/{{ item }}
      dest: "/root/bin/{{ item }}"
      mode: 0777
    with_items:
    - common.sh
    - order_svc.sh
    - jq-linux64

  - name: Change mod - order_svc.sh
    command: "chmod +x /root/bin/order_svc.sh /root/bin/jq /root/bin/common.sh"

  - name: Create credential.rc
    template:
      src: templates/credentials.rc.j2
      dest: "/root/credential.rc"

  - name: Deploy production environment in OpenTLC
    shell: "source /root/credential.rc"
    shell: "/root/bin/order_svc.sh -c 'OPENTLC Automation' -i 'Three Tier Application' -t -y"
     
  - name: Pause for 15 minutes to wait for production environment to be provisioned in AWS before ending play
    pause:
      minutes: 2
