---
- name: create /bin/ directory under root
  hosts: tag_AnsibleGroup_bastion
  gather_facts: true
  become: yes
  tasks:
    file:
      path: /root/bin/
      state: directory
      mode: 0755

- name: download the scripts common.sh, oder_svc.sh and jq
  get_url:
    url: "http://www.opentlc.com/download/ansible_bootcamp/scripts/{{ item }}"
    dest: /root/bin/{{ item }}
    mode: 0755
  with_items:
  - common.sh
  - order_svc.sh
  - jq-linux64

- name: create credentials
  template:
    src: templates/credentials.rc.j2
    dest: /root/bin/credentials.rc

- name: Deploy prod env
  command: "source /root/bin/credentials.rc && /root/bin/order_svc.sh -c 'OPENTLC Automation' -i 'Three Tier Application' -t 1 -y"

- name: pause for 15 min
  pause:
    minutes: 15
