---
- name: Provision Production Environment
  hosts: bastion
  gather_facts: true
  become: yes
  
  tasks:
  - name: Create bin directory
    file:
      path: "{{ ansible_env.HOME }}/bin"
      state: directory
      mode: 0777

  - name: Download common.sh and order_svc.sh
    get_url:
      url: http://www.opentlc.com/download/ansible_bootcamp/scripts/{{ item }}
      dest: "{{ ansible_env.HOME }}/{{ item }}"
      mode: 0777
    with_items:
    - common.sh
    - order_svc.sh
    - jq-linux64

  - name: Change mod - order_svc.sh
    shell: "chmod +x {{ ansible_env.HOME }}/order_svc.sh {{ ansible_env.HOME }}/common.sh "

  - name: Create credential.rc
    template:
      src: templates/credentials.rc.j2
      dest: "{{ ansible_env.HOME }}/credential.rc"

  - name: Deploy production environment in OpenTLC
    command: "source '{{ ansible_env.HOME }}/credential.rc' ; '{{ ansible_env.HOME }}/bin/order_svc.sh' -c 'OPENTLC Automation' -i 'Three Tier Application' -t 1 -y"
   

  - name: Pause for 15 minutes to wait for production environment to be provisioned in AWS before ending play
    pause:
      minutes: 2
