---
- name: Provision Production env
  hosts: bastion
  gather_facts: true
  become: yes
  tasks: 
  - name: Install latest version of jq
    yum: 
      name: jq
      state: latest
  - name: create bin directory
    file: 
      path: "/tmp/bin"
      state: directory
      mode: 0755
  - name: download common.sh and order_svc.sh
    get_url:
      url: http://www.opentlc.com/download/ansible_bootcamp/scripts/{{item }}
      dest: "/tmp/{{ item }}"
      mode: 0755
    with_items:
    - common.sh
    - order_svc.sh
  - name: download jq-linux64
    shell: "wget http://www.opentlc.com/download/ansible_bootcamp/scripts/jq-linux64 -O /tmp/bin/jq"
  - name: change mode +x
    shell: "chmod +x /tmp/order_svc.sh /tmp/bin/jq"
  - name: create credentials.rc
    template:
      src: templates/credentials.rc.j2
      dest: "/tmp/credentials.rc"
  - name: Deploy production env in OPENTLC
    shell: "source /tmp/credentials.rc && /tmp/order_svc.sh"
  - name: Pause for 15 min for the env to come up
    pause:
      minutes: 15
