---
- name: Gather Facts
  hosts: jumpbox
  become: ture
  tasks:
  - name: Gather facts
    include_role:
       name: osp-facts
    tags:
     - get_openstack_vm_inventory

- name: setup load-balancer tier
  hosts: frontends
  become: true
  gather_facts: true
  roles:
    - {name: base-configs, tags: base-configs}
    - {name: lbaas, tags: [lbs, haproxy]}




