---
# Initial, common, system setup steps
- name: enable sudo without tty for some ansible commands
  replace:
    dest: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  template:
    src: templates/template_repos.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644
 
- name: install base tools and packages
  yum:
    name: "{{ item }}" 
    state: latest
  with_items:
    - httpie
    - python-pip
